---
chef_license: accept

driver:
  name: docker

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  product_version: 14.12
  product_name: chef

verifier:
  name: inspec

platforms:
  # default driver, vagrant
  - name: debian
    driver_config:
      image: debian:stretch

suites:
  - name: default
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
  - name: switch
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            network:
              mode: "switch"
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"

  - name: avahi-zeroconf
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
              avahi_zeroconf_enabled: true
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
