---
# this is still very early - it seems to be significanly slower then `docken`
# and yet seems to fail connecting using SSH when we start systemd
# currently this is not working but it is WIP

driver:
  cap_add:
    - SYS_ADMIN
  disable_upstart: false
  hostname: tincvpn3
  name: docker
  privileged: yes
  provision_command:
    - apt-get install systemd -y
  run_command: /bin/systemd
  socket: unix:///var/run/docker.sock

provisioner:
  always_update_cookbooks: true
  chef_license: accept
  name: chef_zero
  nodes_path: test/fixtures/nodes

verifier:
  name: inspec

platforms:
  # default driver, vagrant
  - name: debian
    driver_config:
      image: debian:stretch

suites:
  - name: default-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              connect_to:
                - tincnode1
                - tincnode2
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/default
  - name: custom-network-without-host-name
    attributes:
      tincvpn:
        networks:
          custom:
            host:
              connect_to:
                - tinccustomnode1
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/custom_network
  - name: switch-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
            network:
              mode: switch
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/switch
  - name: avahi-zeroconf-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              avahi_zeroconf_enabled: true
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
              connect_to:
                - tincnode1
                - tincnode2
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/avahi_zeroconf
  - name: default-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              connect_to:
                - tincnode1
                - tincnode2
              name: tincvpn3
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/default
  - name: switch-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              name: tincvpn3
            network:
              mode: switch
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/switch
  - name: avahi-zeroconf-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              avahi_zeroconf_enabled: true
              connect_to:
                - tincnode1
                - tincnode2
              name: tincvpn3
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/avahi_zeroconf
