---
driver:
  hostname: tincvpn3 # Hostname is used in the tests so should be fixed
  name: dokken
  privileged: true  # because Docker and SystemD/Upstart
  cap_add:
    - SYS_ADMIN

provisioner:
  always_update_cookbooks: true
  chef_license: accept
  client_rb:
    chef_license: accept
  name: dokken
  nodes_path: test/fixtures/nodes

transport:
  name: dokken

platforms:
  - name: debian-9.9
    driver:
      image: debian:stretch
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN apt-get install -y systemd net-tools
      pid_one_command: /bin/systemd
  - name: debian-10
    driver:
      image: debian:buster
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN apt-get install -y systemd
      pid_one_command: /bin/systemd

verifier:
  name: inspec

suites:
  - name: default-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              connect_to:
                - tincnode1
                - tincnode2
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
            network:
              tunneladdr: 172.25.0.1
              tunnelnetmask: 255.255.255.0
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/default
  - name: custom-network-without-host-name
    attributes:
      tincvpn:
        networks:
          custom:
            host:
              connect_to:
                - tinccustomnode1
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/custom_network
  - name: switch-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
            network:
              mode: switch
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/switch
  - name: avahi-zeroconf-without-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              avahi_zeroconf_enabled: true
              connect_to:
                - tincnode1
                - tincnode2
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/avahi_zeroconf
  - name: default-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              connect_to:
                - tincnode1
                - tincnode2
              name: tincvpn3
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
            network:
              tunneladdr: 172.25.0.1
              tunnelnetmask: 255.255.255.0
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/default
  - name: switch-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              name: tincvpn3
            network:
              mode: switch
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/switch
  - name: avahi-zeroconf-with-host-name
    attributes:
      tincvpn:
        networks:
          default:
            host:
              address: 15.0.0.16
              avahi_zeroconf_enabled: true
              connect_to:
                - tincnode1
                - tincnode2
              name: tincvpn3
              subnets:
                - 10.3.0.0/24
                - 172.3.0.0/16
    run_list:
      - recipe[tincvpn::default]
    verifier:
      inspec_tests:
        - test/integration/avahi_zeroconf
