---
verifier:
  name: inspec

platforms:
  # default driver, vagrant
  - name: debian-9.9
    driver:
      name: vagrant
    provisioner:
      name: chef_zero
      always_update_cookbooks: true
      nodes_path: test/fixtures/nodes
      product_version: 14.12
      product_name: chef
      chef_license: accept

  # dokken based
  - name: dokken-debian
    driver:
      name: dokken
      # Hostname is used in the tests so should be fixed
      hostname: tincvpn3
      # pid_one_command: /bin/systemd
      image: dokken/debian-9
      # image: debian:stretch
      intermediate_instructions:
        # ensure the apt-index is not deleted
        - RUN rm /etc/apt/apt.conf.d/docker-clean
    provisioner:
      name: dokken
      chef_license: accept
      always_update_cookbooks: true
      nodes_path: test/fixtures/nodes

    transport:
      name: dokken

suites:
  - name: default
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
  - name: switch
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            network:
              mode: "switch"
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
  - name: avahi-zeroconf
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
              avahi_zeroconf_enabled: true
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
