---
# this is still very early - it seems to be significanly slower then `docken`
# and yet seems to fail connecting using SSH when we start systemd

driver:
  name: docker
  priviled: yes
  # TODO: doing that, we cannot connect using SSH any longer
  #  not using it, does lead to issues with our cookbook since we expect systemd
  # run_command: /bin/systemd
  disable_upstart: false
  cap_add:
    - SYS_ADMIN
  socket: unix:///var/run/docker.sock
provisioner:
  name: chef_zero
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes
  chef_license: accept

verifier:
  name: inspec

platforms:
  # default driver, vagrant
  - name: debian
    driver_config:
      image: debian:stretch

suites:
  - name: default
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
  - name: switch
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            network:
              mode: "switch"
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"

  - name: avahi-zeroconf
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
              avahi_zeroconf_enabled: true
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
