---
driver:
  name: dokken
  #image: debian:stretch # for now avoiding to use dokken/debian-9
  privileged: true  # because Docker and SystemD/Upstart

provisioner:
  name: dokken
  chef_license: accept
  client_rb:
    chef_license: accept
  always_update_cookbooks: true
  nodes_path: test/fixtures/nodes

transport:
  name: dokken

platforms:
  - name: debian-9.9
    hostname: tincvpn3 # Hostname is used in the tests so should be fixed
    driver:
      image: debian:stretch
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN apt-get install -y systemd

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
  - name: switch
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            network:
              mode: "switch"
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
  - name: avahi-zeroconf
    run_list:
      - recipe[tincvpn::default]
    attributes:
      tincvpn:
        networks:
          default:
            host:
              name: 'tincvpn3'
              address: "15.0.0.16"
              avahi_zeroconf_enabled: true
              subnets:
                - '10.3.0.0/24'
                - '172.3.0.0/16'
              connect_to:
                - 'tincnode1'
                - 'tincnode2'
