dist: xenial
language: ruby

rvm:
  - 2.5.4

cache: bundler
sudo: required

services:
  - docker

env:
  global:
    - CHEF_LICENSE="accept-no-persist"
  - KITCHEN_YAML=.kitchen.dokken.yml
  - KITCHEN_YAML=.kitchen.docker.yml
before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk

install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant'

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec bundle exec docker version
  - chef exec bundle exec kitchen --version
  - time chef exec bundle exec kitchen test -l debug
