dist: xenial
language: ruby

rvm:
  - 2.5.4

cache: bundler
sudo: required

services:
  - docker

env:
  global:
    - KITCHEN_YAML=.kitchen.dokken.yml
    - PLATFORM=dokken-debian
    - CHEF_LICENSE="accept-no-persist"

before_install: curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk

install: chef exec bundle install --jobs=3 --retry=3 --without='vagrant' --without='docker'

before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - chef exec bundle exec docker version
  - chef exec bundle exec kitchen --version
  - time chef exec bundle exec kitchen test ${PLATFORM} -l debug
